# Generated by Django 6.1 on 2026-08-31 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Biznes nomi')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.CharField(blank=True, help_text="Masalan: IT, Ta'lim, Savdo, Restoran, Xizmat ko'rsatish", max_length=100, verbose_name='Biznes sohasi / Faoliyat turi')),
                ('website', models.URLField(blank=True, help_text="https://misol.uz ko'rinishida", max_length=255, null=True, verbose_name='Vebsayt manzili')),
                ('telegram', models.CharField(blank=True, help_text='@username yoki havola shaklida', max_length=100, verbose_name='Telegram manzili')),
                ('instagram', models.CharField(blank=True, help_text='@username yoki havola shaklida', max_length=100, verbose_name='Instagram manzili')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Aloqa telefoni')),
                ('description', models.TextField(help_text="Biznesingiz, ko'rsatadigan xizmatlar yoki mahsulotlar haqida batafsil ma'lumot", verbose_name="Biznes haqida ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Biznes',
                'verbose_name_plural': 'Bizneslar',
                'ordering': ['-created_at'],
            },
        ),
    ]
