# Generated by Django 6.1 on 2026-08-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('endpoint', models.CharField(max_length=50, verbose_name="So'rov turi (Text/Voice)")),
                ('user_input', models.TextField(blank=True, null=True, verbose_name="Foydalanuvchi so'rovi")),
                ('error_message', models.TextField(verbose_name='Xatolik xabari')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Batafsil (Traceback)')),
            ],
            options={
                'verbose_name': 'Chat Xatolik',
                'verbose_name_plural': 'Chat Xatoliklari',
                'ordering': ['-timestamp'],
            },
        ),
    ]
