# Generated by Django 6.1 on 2026-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaterrorlog',
            name='platform',
            field=models.CharField(default='web', max_length=50, verbose_name='Platforma'),
        ),
    ]
