# Generated by Django 6.1 on 2026-08-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chaterrorlog_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('platform', models.CharField(default='web', max_length=50, verbose_name='Platforma')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('answered', 'Javob berildi')], default='pending', max_length=20, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Javobsiz Savol',
                'verbose_name_plural': 'Javobsiz Savollar',
                'ordering': ['-timestamp'],
            },
        ),
    ]
