# Generated by Django 6.1 on 2026-08-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_unansweredquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name="Foydalanuvchi so'rovi")),
                ('platform', models.CharField(default='web', max_length=50, verbose_name='Platforma')),
                ('device', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qurilma')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Manzil')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foydalanuvchi ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': "Chat So'rov",
                'verbose_name_plural': "Chat So'rovlari",
                'ordering': ['-timestamp'],
            },
        ),
    ]
