# Generated by Django 6.1 on 2026-08-17 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatrequestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unansweredquestion',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Operator javobi'),
        ),
        migrations.AddField(
            model_name='unansweredquestion',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqt'),
        ),
        migrations.AddField(
            model_name='unansweredquestion',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Javob bergan operator'),
        ),
        migrations.AddField(
            model_name='unansweredquestion',
            name='feedback',
            field=models.CharField(blank=True, choices=[('yes', 'Ha, qoniqdim'), ('partially', 'Qisman'), ('no', "Yo'q, qoniqmadim")], max_length=20, null=True, verbose_name='Foydalanuvchi bahosi'),
        ),
        migrations.AddField(
            model_name='unansweredquestion',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Parol'),
        ),
        migrations.AddField(
            model_name='unansweredquestion',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Ticket ID'),
        ),
    ]
