# Generated by Django 6.1 on 2026-09-17 16:25

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models

from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_remove_business_category'),
    ]

    operations = [
        CreateExtension('vector'),
        migrations.CreateModel(
            name='BusinessKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='Qaysi sahifadan scrape qilingan', max_length=500, verbose_name='Manba sahifa URL')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Sahifa sarlavhasi')),
                ('content', models.TextField(help_text="500-1000 so'zlik matn bo'lagi", verbose_name='Chunk matni')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Embedding vektori (768-d)')),
                ('chunk_index', models.PositiveIntegerField(default=0, verbose_name='Chunk tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='businesses.business', verbose_name='Biznes')),
            ],
            options={
                'verbose_name': 'Bilim Chunki',
                'verbose_name_plural': 'Bilimlar Bazasi',
                'ordering': ['business', 'source_url', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='knowledge_embedding_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
