# Generated by Django 6.1 on 2026-09-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_remove_business_category'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Jarayonda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Xatolik'), ('no_data', "Ma'lumot topilmadi")], default='running', max_length=20, verbose_name='Holat')),
                ('pages_scraped', models.PositiveIntegerField(default=0, verbose_name='Scrape qilingan sahifalar')),
                ('chunks_stored', models.PositiveIntegerField(default=0, verbose_name='Saqlangan chunklar soni')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='Manba URL')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik xabari')),
                ('duration_seconds', models.FloatField(default=0, verbose_name='Davomiyligi (soniya)')),
                ('triggered_by', models.CharField(default='manual', help_text='manual, auto, onboarding', max_length=30, verbose_name='Kim tomonidan')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='businesses.business', verbose_name='Biznes')),
            ],
            options={
                'verbose_name': 'Sinxronizatsiya Logi',
                'verbose_name_plural': 'Sinxronizatsiya Loglari',
                'ordering': ['-started_at'],
            },
        ),
    ]
