# Generated by Django 6.1 on 2026-08-31 18:40

import apps.chatbot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, default=apps.chatbot.models.generate_api_key, max_length=64, unique=True, verbose_name='Vidjet API Kaliti')),
                ('bot_name', models.CharField(default='AI Yordamchi', max_length=100, verbose_name='Bot nomi')),
                ('welcome_message', models.TextField(default='Assalomu alaykum! Sizga qanday yordam bera olaman?', verbose_name='Salomlashish matni')),
                ('theme_color', models.CharField(default='#4f46e5', max_length=20, verbose_name='Asosiy rang kodi (Hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Chatbot faolmi?')),
                ('extra_knowledge', models.TextField(blank=True, help_text="Masalan: Ish vaqti: 09:00 - 18:00, Toshkent bo'yicha yetkazib berish bepul, To'lov usullari: Click, Payme, Naqd.", verbose_name="Qo'shimcha ma'lumotlar va FAQ")),
                ('suggested_questions', models.TextField(blank=True, default="Xizmatlaringiz haqida ma'lumot bering\nQanday bog'lansam bo'ladi?\nIsh vaqtingiz qachon?", help_text='Har bir qatorda 1 ta tezkor savol yozing', verbose_name='Tavsiya etilgan tezkor savollar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_config', to='businesses.business', verbose_name='Biznes')),
            ],
            options={
                'verbose_name': 'Chatbot Sozlamasi',
                'verbose_name_plural': 'Chatbot Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chatbot.chatbotconfig')),
            ],
            options={
                'verbose_name': 'Suhbat Sessiyasi',
                'verbose_name_plural': 'Suhbat Sessiyalari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Mijoz'), ('assistant', 'AI Bot')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatbotconfig')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['created_at'],
            },
        ),
    ]
