# Generated by Django 6.1 on 2026-08-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-last_message_at', '-created_at'], 'verbose_name': 'Murojaat Sessiyasi', 'verbose_name_plural': 'Murojaatlar (Leads)'},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name="So'nggi xabar vaqti"),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izoh / Eslatma'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('archived', 'Arxiv')], default='new', max_length=20, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Murojaatchi ismi'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Birinchi murojaat'),
        ),
    ]
