# Generated by Django 6.1 on 2026-09-01 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatsession_options_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='team.staffmember', verbose_name='Yuborgan xodim'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to='team.staffmember', verbose_name='Biriktirilgan xodim'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eskalatsiya vaqti'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='escalation_status',
            field=models.CharField(choices=[('ai', 'AI Javob bermoqda'), ('waiting_operator', 'Operator javobi kutilmoqda'), ('operator_active', 'Operator muloqotda'), ('escalated_supervisor', 'Supervisorga kechiktirildi'), ('resolved', 'Hal qilindi')], default='ai', max_length=30, verbose_name='Eskalatsiya holati'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_escalated',
            field=models.BooleanField(default=False, verbose_name='Operatorga uzatilganmi?'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA muddati'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'Mijoz'), ('assistant', 'AI Bot'), ('staff', 'Xodim (Operator/Supervisor)')], max_length=20),
        ),
    ]
