# Generated by Django 6.1 on 2026-09-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_sender_staff_chatsession_assigned_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfig',
            name='telegram_bot_active',
            field=models.BooleanField(default=False, verbose_name='Telegram Bot faolmi?'),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='telegram_bot_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Bot Nomi'),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='@BotFather dan olingan HTTP API Token', max_length=200, null=True, verbose_name='Telegram Bot Tokeni'),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='telegram_bot_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Bot Username'),
        ),
    ]
