# Generated by Django 6.1 on 2026-09-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatbotconfig_telegram_bot_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfig',
            name='response_delay_enabled',
            field=models.BooleanField(default=False, verbose_name='Inson kabi kechiktirib javob berish (Human-like delay)'),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='response_delay_seconds',
            field=models.IntegerField(choices=[(5, '5 soniya'), (10, '10 soniya')], default=5, verbose_name='Kechikish davomiyligi'),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='split_messages',
            field=models.BooleanField(default=True, verbose_name="Matnlarni bo'laklarga ajratib yuborish"),
        ),
    ]
