# Generated by Django 6.1 on 2026-09-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatbotconfig_response_delay_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfig',
            name='first_message_delay_seconds',
            field=models.IntegerField(default=5, verbose_name='Birinchi xabarga kechikish (soniya)'),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='subsequent_message_delay_seconds',
            field=models.IntegerField(default=10, verbose_name='Keyingi xabarlarga kechikish (soniya)'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='response_delay_enabled',
            field=models.BooleanField(default=True, verbose_name='Inson kabi kechiktirib javob berish (Human-like delay)'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='response_delay_seconds',
            field=models.IntegerField(default=5, verbose_name='Kechikish davomiyligi'),
        ),
    ]
