# Generated by Django 6.1 on 2026-09-01 06:02

import apps.team.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('chatbot', '0002_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xodim ismi')),
                ('role', models.CharField(choices=[('operator', 'Operator (Mijozlarga javob beruvchi)'), ('supervisor', 'Supervisor (Nazoratchi va Boshqaruvchi)')], default='operator', max_length=20, verbose_name='Xodim roli')),
                ('telegram_username', models.CharField(blank=True, help_text='@username shaklida kiriting', max_length=100, verbose_name='Telegram @username')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('auth_token', models.CharField(default=apps.team.models.generate_staff_token, max_length=64, unique=True, verbose_name='TMA Kirish Tokeni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Xodim faolmi?')),
                ('is_online', models.BooleanField(default=True, verbose_name='Navbatchilikda / Onlayn')),
                ('sla_minutes', models.PositiveIntegerField(default=5, help_text='Operator ushbu vaqt ichida javob bermasa, chat avtomatik ravishda Supervisorga eskalatsiya qilinadi', verbose_name='SLA Javob berish vaqti (daqiqa)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='businesses.business', verbose_name='Biznes')),
            ],
            options={
                'verbose_name': 'Xodim (Operator/Supervisor)',
                'verbose_name_plural': 'Xodimlar (Operatorlar & Supervisorlar)',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_reason', models.TextField(blank=True, verbose_name='Eskalatsiya sababi')),
                ('escalated_to_operator_at', models.DateTimeField(auto_now_add=True, verbose_name='Operatorga yuborilgan vaqt')),
                ('operator_first_replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Operatorning 1-javobi vaqti')),
                ('escalated_to_supervisor_at', models.DateTimeField(blank=True, null=True, verbose_name="Supervisorga o'tgan vaqt")),
                ('is_sla_breached', models.BooleanField(default=False, verbose_name='SLA buzilganmi (kechikkanmi)?')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('resolved_by', models.CharField(blank=True, choices=[('operator', 'Operator tomonidan'), ('supervisor', 'Supervisor tomonidan'), ('ai', 'AI tomonidan')], max_length=20, verbose_name='Kim tomonidan hal qilindi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='chatbot.chatsession', verbose_name='Suhbat')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_escalations', to='team.staffmember', verbose_name='Biriktirilgan operator')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_escalations', to='team.staffmember', verbose_name='Eskalatsiya qilingan supervisor')),
            ],
            options={
                'verbose_name': 'Eskalatsiya Tarixi',
                'verbose_name_plural': 'Eskalatsiyalar Tarixi',
                'ordering': ['-escalated_to_operator_at'],
            },
        ),
    ]
